version: '3'

services:
  traefik:
    image: traefik:v3.0
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`traefik.localhost`)"
      - "traefik.http.services.api.loadbalancer.server.port=8080"

  backend:
    build:
      dockerfile: Dockerfile
      context: back
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.backend.loadbalancer.server.port=8081"
    ports:
      - "8081:8081"
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock

  frontend:
    build:
      dockerfile: Dockerfile
      context: front
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`fire.allanbenameur.com`)"
      - "traefik.http.routers.frontend.entrypoints=web"
      - "traefik.http.services.frontend.loadbalancer.server.port=3000"
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - ORIGIN=http://fire.allanbenameur.com
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock