version: '3'

services:
  traefik:
    image: traefik:v3.1
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.myresolver.acme.email=benameurallan06@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "./letsencrypt:/letsencrypt"
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`traefik.localhost`)"
      - "traefik.http.services.api.loadbalancer.server.port=8080"

  backend:
    build:
      dockerfile: Dockerfile
      context: back
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.backend.loadbalancer.server.port=8081"
    ports:
      - "8081:8081"
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock

  frontend:
    build:
      dockerfile: Dockerfile
      context: front
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`fire.allanbenameur.com`)"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.services.frontend.loadbalancer.server.port=3000"
      - traefik.http.routers.frontend.tls=true
      - traefik.http.routers.frontend.tls.certresolver=myresolver
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - ORIGIN=https://fire.allanbenameur.com
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock