// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"database/sql"
	"time"
)

type Application struct {
	ID     string `json:"id"`
	Name   string `json:"name"`
	Status string `json:"status"`
	Image  string `json:"image"`
	Port   string `json:"port"`
}

type Deployment struct {
	ID         string       `json:"id"`
	AppID      string       `json:"app_id"`
	Status     string       `json:"status"`
	CreatedAt  time.Time    `json:"created_at"`
	FinishedAt sql.NullTime `json:"finished_at"`
}

type Token struct {
	Token     string    `json:"token"`
	UserID    string    `json:"user_id"`
	ExpiresAt time.Time `json:"expires_at"`
}

type User struct {
	ID       string `json:"id"`
	Email    string `json:"email"`
	Name     string `json:"name"`
	Password string `json:"password"`
}
