// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: deployments.sql

package db

import (
	"context"
	"database/sql"
)

const createDeployment = `-- name: CreateDeployment :one
INSERT INTO deployments (id, app_id, status, created_at) 
    VALUES (?, ?, ?, now()) 
    RETURNING id, app_id, status, created_at, finished_at
`

type CreateDeploymentParams struct {
	ID     string `json:"id"`
	AppID  string `json:"app_id"`
	Status string `json:"status"`
}

func (q *Queries) CreateDeployment(ctx context.Context, arg CreateDeploymentParams) (Deployment, error) {
	row := q.db.QueryRowContext(ctx, createDeployment, arg.ID, arg.AppID, arg.Status)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.Status,
		&i.CreatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const updateDeployment = `-- name: UpdateDeployment :exec
UPDATE deployments
    SET status = ?, finished_at = ?
    WHERE id = ?
`

type UpdateDeploymentParams struct {
	Status     string       `json:"status"`
	FinishedAt sql.NullTime `json:"finished_at"`
	ID         string       `json:"id"`
}

func (q *Queries) UpdateDeployment(ctx context.Context, arg UpdateDeploymentParams) error {
	_, err := q.db.ExecContext(ctx, updateDeployment, arg.Status, arg.FinishedAt, arg.ID)
	return err
}
