// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

type Application struct {
	ID    string `json:"id"`
	Name  string `json:"name"`
	Image string `json:"image"`
	Port  int64  `json:"port"`
}